const SAVE_MAIN_POSTS = "SAVE_MAIN_POSTS";
const SAVE_FEATURED_POSTS = "SAVE_FEATURED_POSTS";
const SAVE_ALL_POST = "SAVE_ALL_POST";
const SAVE_DETAIL_POST = "SAVE_DETAIL_POST";

export { SAVE_MAIN_POSTS, SAVE_FEATURED_POSTS, SAVE_ALL_POST, SAVE_DETAIL_POST };
