const SAVE_TOKEN = "SAVE_TOKEN";
const SAVE_CURRENT_USER = "SAVE_CURRENT_USER";

const SAVE_CURRENT_SUBCRIPTION = "SAVE_CURRENT_USER";
const GET_ALL_SUBCRIPTIONS = "GET_ALL_SUBCRIPTIONS";

export { SAVE_TOKEN, SAVE_CURRENT_USER , SAVE_CURRENT_SUBCRIPTION, GET_ALL_SUBCRIPTIONS};
